# Spring Boot Application Configuration
server.port=8080
spring.application.name=aceitedig

# Logging configuration
logging.level.root=INFO
logging.level.br.com.bradesco.cnsg.srv.formata.aceitedig=DEBUG